# This file is auto-generated by prompt-gen/generate.js
# DO NOT EDIT DIRECTLY - edit prompts.json and run: node implementations/prompt-gen/generate.js

MINIMAL_BASE = """Output in LSF format:
$o~=object, $f~=field, $v~=value, $t~=type(n=int,f=float,b=bool,d=date,z=null)
NO quotes/brackets. Arrays: repeat $v~. Continuous line."""

MINIMAL_EXAMPLE = """Example: $o~$f~name$v~John$f~age$v~30$t~n$f~tags$v~a$v~b"""

DETAILED_BASE = """Generate output in LSF (LLM-Safe Format):

TOKENS:
- $o~ = start object
- $f~ = field name follows
- $v~ = value follows  
- $t~ = type hint follows (single character)

TYPES:
- n = integer (e.g., 42)
- f = float (e.g., 3.14)
- b = boolean (true/false)
- d = datetime (ISO format)
- s = string (optional, default)
- z = null

RULES:
1. NO quotes, brackets, or commas anywhere
2. NO newlines between tokens (continuous stream)
3. Arrays: repeat $v~ for same field
4. Multi-line strings: write actual newlines, not \n
5. Write all special characters as-is
6. NO escaping - write everything literally"""

DETAILED_EXAMPLE = """EXAMPLE:
$o~$f~name$v~John Doe$f~age$v~30$t~n$f~active$v~true$t~b$f~tags$v~admin$v~user"""


def get_prompt_text(include_example: bool, style: str) -> str:
    """Get the prompt text for the given style."""
    if style == "detailed":
        base = DETAILED_BASE
        example = DETAILED_EXAMPLE
    else:
        base = MINIMAL_BASE
        example = MINIMAL_EXAMPLE
    
    return base + "\n" + example if include_example else base
